---
    name: Build & upload PyPI package

    on:
      release:
        types:
          - published
      workflow_dispatch:

    jobs:
      tests:
        uses: "./.github/workflows/tests.yaml"

      # Always build & lint package.
      build-package:
        name: Build & verify package
        needs:
          - tests
        runs-on: ubuntu-latest
        permissions:
          attestations: write
          id-token: write

        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
              persist-credentials: false

          - uses: hynek/build-and-inspect-python-package@v2
            with:
              attest-build-provenance-github: 'true'

      # Upload to real PyPI on GitHub Releases.
      release-pypi:
        name: Publish released package to pypi.org
        environment: release-pypi
        if: github.event.action == 'published'
        runs-on: ubuntu-latest
        needs:
          - build-package
        permissions:
          id-token: write

        steps:
          - name: Download packages built by build-and-inspect-python-package
            uses: actions/download-artifact@v4
            with:
              name: Packages
              path: dist

          - name: Upload package to PyPI
            uses: pypa/gh-action-pypi-publish@release/v1

