
name: Build and test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run install
      run: |
        _PIP_USE_IMPORTLIB_METADATA=0  make install
    - name: Run checkers
      run: |
        make check
    - name: Run tests
      run: |
        make test
