
name: Build and test

on: [push]

jobs:
   test-and-check:
    strategy:
      matrix:
        python-version:
        - "3.11"
        - "3.12"
        - "3.13"
    runs-on: ubuntu-latest
    env:
      PRIMARY_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run install
      run: |
        make install
    - name: Run checkers
      run: |
        make check
    - name: Run tests
      run: |
        make test
